name: online_consultation_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^4.0.3
  image_picker: ^0.8.7
  intl: ^0.17.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/picture/
    - assets/lottie/
